global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'my-service'
rule_files:
scrape_configs:
  - job_name: my-service
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'my-service:8080'