global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'my_service'
rule_files:
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
          - host.docker.internal:9090
  - job_name: my_service
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 0.0.0.0:8080
          - host.docker.internal:8080